project:
  type: website
  output-dir: docs
  resources:
    - my_images/
    - itinerary-one-pager.pdf

website:
  title: "Carsen's Bachelorette Weekend"
  navbar: false

format:
  html:
    theme: none
    css: styles.css
    toc: false
    page-layout: custom
    embed-resources: false
